spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://config-service:8888"

server:
  port: 8081

app:
  notification-service-url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8087}
