spring:
  application:
    name: resultat-service
  config:
    import: "optional:configserver:http://config-service:8888"
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://postgres-resultat:5432/residanat_resultat_db
    username: postgres
    password: system
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
