server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://postgres-resultat:5432/residanat_resultat_db
    username: postgres
    password: system
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
