spring:
  cloud:
    gateway:
      default-filters:
        - DeduplicateResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: concours-service
          uri: lb://concours-service
          predicates:
            - Path=/api/concours/**
        - id: dossier-service
          uri: lb://dossier-service
          predicates:
            - Path=/api/dossiers/**
        - id: convocation-service
          uri: lb://convocation-service
          predicates:
            - Path=/api/convocations/**
      globalcors:
        add-to-chain: true
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:4200"
            allowedMethods: 
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "PATCH"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
