server.port=8082

spring.application.name=concours-service

spring.datasource.url=jdbc:postgresql://localhost:5432/residanat_concours_db
spring.datasource.username=postgres
spring.datasource.password=Ebtissem.1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration JWT (doit matcher celle du service d'authentification)
jwt.secret=CeciEstUneCleSecreteTresLonguePourResidanatTN2026!
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logs
logging.level.tn.sante.concours=DEBUG
